server:
  port: 9007
spring:
  application:
    name: tenquare-search #指定服务名
  data:
    elasticsearch:
      cluster-nodes: 192.168.204.128:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true