server: 
  port: 9010
spring: 
  application:  
    name: car-work  #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.25.217:3306/cyq?characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      max-lifetime: 1200000
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true
feign:
  hystrix:
    enabled: true
