server: 
  port: 9004
spring: 
  application:  
    name: article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.25.217:3306/cyq?characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      max-lifetime: 1200000
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 47.100.25.217
#  devtools:
#    restart:
#      enabled: true
##      additional-paths: src/main/java #重启目录
#      exclude: WEB-INF/**
  freemarker:
    cache: false  #页面不加载缓存，修改即时生效
jwt:
  config:
    key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true